name: Set up dependencies
author: LayZeeDK
description: Set up Node.js, npm, and install dependencies

runs:
  using: composite

  steps:
    - uses: actions/setup-node@v5
      with:
        cache: npm
        node-version-file: .node-version
    - name: Install dependencies
      run: npm ci
      shell: bash
