name: Set up dependencies

runs:
  using: composite

  steps:
    - uses: actions/setup-node@v3
      with:
        cache: yarn
        node-version-file: '.nvmrc'
    - name: Install dependencies
      run: yarn install --frozen-lockfile --non-interactive
      shell: bash
