name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Build package
        run: npm run build
      - name: Build Storybook
        run: npm run build:storybook --configuration=ci
      - name: Verify license compliance
        run: npm run verify-license-compliance

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Lint
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Test
        run: npm run test

  e2e:
    name: End-to-end test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: End-to-end test
        run: npm run e2e:ci
