name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  # Group concurrency on workflow, then:
  # - Is merge run? Group on branch name (`refs/heads/main`)
  # - Is pull request? Group on pull request branch name, for example `feat/add-awesome-feature`
  group: >-
    ${{ github.workflow }}-${{
      github.event_name == 'push'
        && github.ref
        || github.head_ref
    }}
  # Run merge workflows in sequence to prevent parallel deployments and releases
  # Cancel stale pull request runs in progress for the same branch
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Build package
        run: npm run build
      - name: Build Storybook
        run: npm run build:storybook --configuration=ci
      - name: Verify license compliance
        run: npm run verify-license-compliance

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Lint
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Test
        run: npm run test

  e2e:
    name: End-to-end test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: End-to-end test
        run: npm run e2e:ci

  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
          filter: tree:0 # Optional, but recommended: reduce the size of the checkout with tree filtering, see https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone/
      - name:
          Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Check formatting
        run: npm run format:check
