name: Copilot Setup Steps

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

env:
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    name: Copilot Environment Setup
    runs-on: ubuntu-latest
    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      # If you want to clone the repository as part of your setup steps, for example to install dependencies, you'll need the `contents: read` permission. If you don't clone the repository in your setup steps, Copilot will do this for you automatically after the steps complete.
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Verify Copilot environment
        run: |
          echo "Node.js version: $(node --version)"
          echo "Yarn version: $(yarn --version)"
          echo "Dependencies installed successfully for Copilot environment"

      - name: Display project information
        run: |
          echo "Project structure:"
          ls -la
          echo ""
          echo "Available scripts:"
          node -e "console.log(Object.keys(require('./package.json').scripts).map(s => '  ' + s).join('\n'))"
